# Generated by Django 4.2.7 on 2023-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_Theme',
        ),
        migrations.AddField(
            model_name='question',
            name='bonne_reponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='reponse_utilisateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(db_column='id_Questions', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
